stages:          # List of stages for jobs, and their order of execution
  - build

upload-container:  
    stage: build
    image: docker:20.10.16
    services:
        - docker:20.10.16-dind
    variables:
        DOCKERTLS_CERTDIR: "/certs"
    before_script:
        - pwd
        - ls -a
        - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
    script:
        - docker build -t ernesto906/cookiegpt .
        - docker push ernesto906/cookiegpt