stages:          # List of stages for jobs, and their order of execution
  - build

upload-container:  
    stage: build
    image: docker:latest
    services:
        - docker:24.0.2-dind
        - docker:20.0.2-git
    variables:
        DOCKERTLS_CERTDIR: "/certs"
    before_script:
        - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
    script:
        - docker build -t ernesto906/cookiegpt .
        - docker push ernesto906/cookiegpt