stages:          # List of stages for jobs, and their order of execution
  - build

upload-container:  
    stage: build
    image: docker:20.10.16
    services:
        - docker:20.10.16-dind
    variables:
        DOCKERTLS_CERTDIR: "/certs"
    before_script:
        - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
        - cd src
    script:
        - docker build -t ernesto906/cookiegpt:1.0.7 .
        - docker push ernesto906/cookiegpt:1.0.7