apiVersion: apps/v1
kind: Deployment
metadata:
  name: cookiegpt-deployment
  labels:
    app: cookiegpt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cookiegpt
  template:
    metadata:
      labels:
        app: cookiegpt
    spec:
      containers:
        - name: cookiegpt
          image: ernesto906/cookiegpt
          ports: 
            - containerPort: 5000
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
